# Generated by Django 5.1.3 on 2024-12-01 06:34

import ckeditor.fields
import django.core.validators
import logistics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('location', models.CharField(max_length=255, verbose_name='Lugar')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, help_text='Tamaño recomendado: 800x400 píxeles. Máximo 2MB.', null=True, upload_to='event_images/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen del Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establecerá automáticamente al crear el evento', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualizará automáticamente al modificar el evento', verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('source', models.CharField(default='', max_length=100, verbose_name='Fuente')),
                ('source_website', models.URLField(blank=True, default='', verbose_name='Sitio web fuente')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('image', models.ImageField(blank=True, help_text='Tamaño recomendado: 800x400 píxeles. Máximo 2MB.', null=True, upload_to='news_images/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen de la Noticia')),
                ('source_url', models.URLField(blank=True, help_text='URL de donde se extrajo la noticia', null=True, verbose_name='URL de origen')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Extraída automáticamente')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del sitio')),
                ('url', models.URLField(verbose_name='URL del sitio')),
                ('selector', models.TextField(help_text='Selector para extraer noticias', verbose_name='Selector CSS/XPath')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_scrape', models.DateTimeField(blank=True, null=True, verbose_name='Última extracción')),
            ],
            options={
                'verbose_name': 'Fuente de noticias',
                'verbose_name_plural': 'Fuentes de noticias',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Rubro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('flag_directorio', models.BooleanField(default=False, verbose_name='Tag en Directorio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('website', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Sitio Web')),
                ('image', models.ImageField(blank=True, help_text='Tamaño recomendado: 300x200 píxeles. Máximo 2MB.', null=True, upload_to='provider_images/', validators=[logistics.validators.validate_image_size], verbose_name='Logo')),
                ('services', models.ManyToManyField(related_name='providers', to='logistics.service', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
