# Generated by Django 5.1.3 on 2024-12-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rubros_interes', models.JSONField()),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción al Newsletter',
                'verbose_name_plural': 'Suscripciones al Newsletter',
            },
        ),
    ]
