# Generated by Django 5.1.3 on 2024-12-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='include_in_newsletter',
            field=models.BooleanField(default=False, help_text='Marcar si esta noticia debe ser incluida en el próximo newsletter', verbose_name='Incluir en Newsletter'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Newsletter')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('content', models.TextField(help_text='Contenido HTML del newsletter generado', verbose_name='Contenido del Newsletter')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Número de Destinatarios')),
                ('news_items', models.ManyToManyField(related_name='newsletters', to='logistics.news', verbose_name='Noticias Incluidas')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_date'],
            },
        ),
    ]
