# Generated by Django 5.1.3 on 2024-12-06 01:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_news_include_in_newsletter_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Contenido HTML del newsletter generado', verbose_name='Contenido del Newsletter'),
        ),
    ]
