# Generated by Django 5.1.3 on 2024-12-07 23:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_newsletter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
