# Generated by Django 5.1.3 on 2024-12-27 01:44

import ckeditor.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_event_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('institution', models.CharField(max_length=255, verbose_name='Entidad o Institución')),
                ('course_type', models.CharField(choices=[('MA', 'Maestría'), ('DI', 'Diplomado'), ('ES', 'Especialización'), ('WE', 'Webinar')], max_length=2, verbose_name='Tipo de Curso')),
                ('modality', models.CharField(choices=[('PR', 'Presencial'), ('ON', 'Online'), ('SI', 'Sincrónica'), ('AS', 'Asincrónica')], max_length=2, verbose_name='Modalidad')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción del Curso')),
                ('is_new', models.BooleanField(default=True, verbose_name='Es Nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
