# Generated by Django 5.1.3 on 2024-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_course_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región'),
        ),
    ]
