# Generated by Django 5.1.3 on 2025-01-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_newslettersubscription_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='region',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='pais',
            field=models.CharField(blank=True, choices=[('México', 'México'), ('Colombia', 'Colombia'), ('España', 'España'), ('Argentina', 'Argentina'), ('Venezuela', 'Venezuela'), ('Perú', 'Perú'), ('Chile', 'Chile'), ('Guatemala', 'Guatemala'), ('Ecuador', 'Ecuador'), ('Cuba', 'Cuba'), ('Bolivia', 'Bolivia'), ('República Dominicana', 'República Dominicana'), ('Honduras', 'Honduras'), ('El Salvador', 'El Salvador'), ('Paraguay', 'Paraguay'), ('Nicaragua', 'Nicaragua'), ('Costa Rica', 'Costa Rica'), ('Puerto Rico', 'Puerto Rico'), ('Panamá', 'Panamá'), ('Uruguay', 'Uruguay'), ('Otro', 'Otro')], max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='sector',
            field=models.CharField(blank=True, choices=[('Aficiones y casinos', 'Aficiones y casinos'), ('Agricultura y ganadería', 'Agricultura y ganadería'), ('Turismo y hostelería', 'Turismo y hostelería'), ('Otro', 'Otro')], max_length=100, null=True, verbose_name='Sector'),
        ),
    ]
