# Generated by Django 5.1.3 on 2025-02-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_newslettersubscription_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='modality',
            field=models.CharField(choices=[('PR', 'Presencial'), ('SS', 'Semipresencial (y sincrónico)'), ('SA', 'Semipresencial (y asincrónico)'), ('OS', 'Online – Sincrónico'), ('OA', 'Online – Asincrónico'), ('ON', 'Online')], max_length=2, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web'),
        ),
    ]
