# Generated by Django 5.1.3 on 2025-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_provider_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='only_members',
            field=models.BooleanField(default=False, verbose_name='Solo Miembros'),
        ),
    ]
