# Generated by Django 5.1.3 on 2025-03-24 03:29

import ckeditor.fields
import logistics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_provider_only_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('image', models.ImageField(blank=True, help_text='Tamaño recomendado: 800x400 píxeles. Máximo 2MB.', null=True, upload_to='article_images/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen del Artículo')),
                ('tags', models.CharField(blank=True, help_text='Separe las etiquetas con comas', max_length=255, verbose_name='Etiquetas')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('include_in_newsletter', models.BooleanField(default=False, help_text='Marcar si este artículo debe ser incluido en el próximo newsletter', verbose_name='Incluir en Newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-date'],
            },
        ),
    ]
