# Generated by Django 5.1.3 on 2025-03-25 00:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('title', models.CharField(max_length=255, verbose_name='Título del anuncio')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Detalle del anuncio')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono de contacto')),
                ('email', models.CharField(max_length=254, verbose_name='Correo electrónico')),
                ('valid_until', models.DateField(verbose_name='Vigencia hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('title', models.CharField(max_length=255, verbose_name='Título del anuncio')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Detalle del anuncio')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono de contacto')),
                ('email', models.CharField(max_length=254, verbose_name='Correo electrónico')),
                ('valid_until', models.DateField(verbose_name='Vigencia hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='logistics.provider', verbose_name='Proveedor (opcional)')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
