# Generated by Django 5.1.3 on 2025-04-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_requirement_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='provider',
        ),
        migrations.AddField(
            model_name='course',
            name='institution_type',
            field=models.CharField(choices=[('UN', 'Universidad'), ('EP', 'Escuela Posgrado'), ('CC', 'Centro de Capacitación'), ('IS', 'Instituto Superior')], default='UN', max_length=2, verbose_name='Tipo de Institución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del curso en soles', max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, choices=[('DC', 'Dirección Comercial'), ('GC', 'Gestión de Compras'), ('LI', 'Logística Internacional'), ('OL', 'Operaciones y Logística'), ('PD', 'Planeamiento de la Demanda'), ('SC', 'Supply Chain Management'), ('TC', 'Tecnología en la Cadena de Suministro')], max_length=2, null=True, verbose_name='Temática'),
        ),
    ]
