# Generated by Django 5.1.3 on 2025-04-18 20:18

import logistics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_remove_proposal_provider_course_institution_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('resource_type', models.CharField(choices=[('LI', 'Libro'), ('DO', 'Documento'), ('AR', 'Artículo'), ('IN', 'Infografía'), ('HC', 'Hoja de Cálculo')], max_length=2, verbose_name='Tipo de Recurso')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Autor')),
                ('author_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono móvil del Autor')),
                ('original_link', models.URLField(blank=True, null=True, verbose_name='Link original del recurso')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mostrar en Novedades')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Archivo')),
                ('image', models.ImageField(blank=True, help_text='Tamaño recomendado: 300x300 píxeles. Máximo 2MB.', null=True, upload_to='resource_images/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen de portada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
