# Generated by Django 5.1.3 on 2025-05-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('MA', 'Maestría'), ('DI', 'Diplomado'), ('ES', 'Especialización'), ('CC', 'Curso Corto'), ('WE', 'Webinar'), ('SE', 'Seminario')], max_length=2, verbose_name='Tipo de Curso'),
        ),
    ]
