# Generated by Django 5.1.3 on 2025-05-11 15:42

import logistics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_alter_course_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('section', models.CharField(choices=[('EDUCACION', 'Educación'), ('DIRECTORIO', 'Directorio'), ('CONTRATAR_OFRECER', 'Contratar/Ofrecer')], max_length=20, verbose_name='Sección')),
                ('image', models.ImageField(help_text='Imagen del banner. Tamaño recomendado según sección: Educación (1200x300px), Directorio (1200x300px), Contratar/Ofrecer (1200x300px). Máximo 2MB.', upload_to='banners/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL de destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
