# Generated by Django 5.1.3 on 2025-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='advertiser',
            field=models.CharField(blank=True, help_text='Empresa o entidad que publica este banner', max_length=100, null=True, verbose_name='Anunciante'),
        ),
    ]
