# Generated by Django 5.1.3 on 2025-05-14 15:11

import django.db.models.deletion
import logistics.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_banner_advertiser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='pais',
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='nombre_completo',
            field=models.CharField(default='Suscriptor', max_length=200, verbose_name='Nombres y Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Imagen del banner. Tamaño recomendado: 940x320px para todos los tipos de banner. Máximo 2MB.', upload_to='banners/', validators=[logistics.validators.validate_image_size], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='fecha_suscripcion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='rol',
            field=models.CharField(max_length=100, verbose_name='Cargo o Rol'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='rubros_interes',
            field=models.JSONField(verbose_name='Rubros de interés'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='sector',
            field=models.CharField(choices=[('Aficiones y casinos', 'Aficiones y casinos'), ('Agricultura y ganadería', 'Agricultura y ganadería'), ('Agua y aguas residuales', 'Agua y aguas residuales'), ('Alimentos', 'Alimentos'), ('Arquitectura', 'Arquitectura'), ('Arte y cultura', 'Arte y cultura'), ('Asistencia y cuidados', 'Asistencia y cuidados'), ('Banca y AFP', 'Banca y AFP'), ('Bebidas alcohólicas', 'Bebidas alcohólicas'), ('Bebidas sin alcohol', 'Bebidas sin alcohol'), ('Centros comerciales y outlets', 'Centros comerciales y outlets'), ('Combustibles fósiles', 'Combustibles fósiles'), ('Comercio al por mayor', 'Comercio al por mayor'), ('Comercio electrónico', 'Comercio electrónico'), ('Comercio internacional', 'Comercio internacional'), ('Construcción naval', 'Construcción naval'), ('Cosmética y cuidado personal', 'Cosmética y cuidado personal'), ('Deporte, fitness y ocio', 'Deporte, fitness y ocio'), ('Educación y ciencia', 'Educación y ciencia'), ('Electrónica', 'Electrónica'), ('Energía y medio ambiente', 'Energía y medio ambiente'), ('Equipamiento del hogar', 'Equipamiento del hogar'), ('Estado de salud', 'Estado de salud'), ('Ferreterías y Bricolage', 'Ferreterías y Bricolage'), ('Finanzas, seguros y bienes inmuebles', 'Finanzas, seguros y bienes inmuebles'), ('Gestión de residuos', 'Gestión de residuos'), ('Hospitales, farmacias y médicos', 'Hospitales, farmacias y médicos'), ('Industria aeroespacial', 'Industria aeroespacial'), ('Industria de defensa', 'Industria de defensa'), ('Industria de software', 'Industria de software'), ('Industria farmacéutica', 'Industria farmacéutica'), ('Ingeniería', 'Ingeniería'), ('Ingeniería civil', 'Ingeniería civil'), ('Juegos de azar', 'Juegos de azar'), ('Juguetes', 'Juguetes'), ('Mascotas', 'Mascotas'), ('Material de oficina', 'Material de oficina'), ('Metalurgia y electrónica', 'Metalurgia y electrónica'), ('Minería, metales y minerales', 'Minería, metales y minerales'), ('Ministerios y Gobierno', 'Ministerios y Gobierno'), ('Mobiliario', 'Mobiliario'), ('Operador Logístico', 'Operador Logístico'), ('Papel y pasta de papel', 'Papel y pasta de papel'), ('Parques y actividades al aire libre', 'Parques y actividades al aire libre'), ('Pesca y acuicultura', 'Pesca y acuicultura'), ('Plástico y caucho', 'Plástico y caucho'), ('Producción de vehículos', 'Producción de vehículos'), ('Productos de limpieza', 'Productos de limpieza'), ('Productos minerales no metálicos', 'Productos minerales no metálicos'), ('Productos químicos y materias primas', 'Productos químicos y materias primas'), ('Publicidad y marketing', 'Publicidad y marketing'), ('Refinerías de petróleo', 'Refinerías de petróleo'), ('Ropa y complementos', 'Ropa y complementos'), ('Salud e higiene', 'Salud e higiene'), ('Sector inmobiliario', 'Sector inmobiliario'), ('Tecnología médica', 'Tecnología médica'), ('Tecnología medioambiental', 'Tecnología medioambiental'), ('Tecnología y telecomunicaciones', 'Tecnología y telecomunicaciones'), ('Turismo y hostelería', 'Turismo y hostelería'), ('Otro', 'Otro')], default='Otro', max_length=100, verbose_name='Sector'),
            preserve_default=False,
        ),
    ]
