# Generated by Django 5.1.3 on 2025-05-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_remove_newslettersubscription_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='rubros_interes',
        ),
    ]
